import {
  useDataTable,
  DataTable,
  useDataTableEvent,
} from "@izumisy/seizen-datatable-react";
import { FilterPlugin } from "@izumisy/seizen-datatable-plugins/filter";
import { ColumnControlPlugin } from "@izumisy/seizen-datatable-plugins/column-control";
import {
  FileExportPlugin,
  CsvExporter,
  JsonlExporter,
  TsvExporter,
} from "@izumisy/seizen-datatable-plugins/file-export";
import { RowDetailPlugin } from "@izumisy/seizen-datatable-plugins/row-detail";
import {
  AvatarName,
  EmailCell,
  DepartmentBadge,
  StatusBadge,
  SalaryCell,
} from "./cells";

const columns = [
  {
    accessorKey: "name",
    header: "Name",
    meta: { filterType: "string" as const },
    cell: ({ row }: { row: { original: { name: string } } }) => (
      <AvatarName name={row.original.name} />
    ),
  },
  {
    accessorKey: "email",
    header: "Email",
    meta: { filterType: "string" as const },
    cell: ({ row }: { row: { original: { email: string } } }) => (
      <EmailCell email={row.original.email} />
    ),
  },
  {
    accessorKey: "department",
    header: "Department",
    meta: {
      filterType: "enum" as const,
      filterEnumValues: ["Engineering", "Design", "Marketing", "Sales"],
    },
    cell: ({ row }: { row: { original: { department: string } } }) => (
      <DepartmentBadge department={row.original.department} />
    ),
  },
  {
    accessorKey: "role",
    header: "Role",
    meta: { filterType: "string" as const },
  },
  {
    accessorKey: "salary",
    header: "Salary",
    meta: { filterType: "number" as const },
    cell: ({ row }: { row: { original: { salary: number } } }) => (
      <SalaryCell salary={row.original.salary} />
    ),
  },
  {
    accessorKey: "status",
    header: "Status",
    meta: {
      filterType: "enum" as const,
      filterEnumValues: ["active", "inactive"],
    },
    cell: ({ row }: { row: { original: { status: string } } }) => (
      <StatusBadge status={row.original.status} />
    ),
  },
];

const data = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice@example.com",
    department: "Engineering",
    role: "Senior Developer",
    salary: 95000,
    status: "active",
    location: "New York",
    phone: "555-0101",
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob@example.com",
    department: "Design",
    role: "UI Designer",
    salary: 78000,
    status: "active",
    location: "San Francisco",
    phone: "555-0102",
  },
  {
    id: 3,
    name: "Carol White",
    email: "carol@example.com",
    department: "Engineering",
    role: "Tech Lead",
    salary: 120000,
    status: "active",
    location: "Chicago",
    phone: "555-0103",
  },
  {
    id: 4,
    name: "David Brown",
    email: "david@example.com",
    department: "Marketing",
    role: "Marketing Manager",
    salary: 85000,
    status: "inactive",
    location: "Boston",
    phone: "555-0104",
  },
  {
    id: 5,
    name: "Eve Davis",
    email: "eve@example.com",
    department: "Sales",
    role: "Sales Rep",
    salary: 65000,
    status: "active",
    location: "Seattle",
    phone: "555-0105",
  },
  {
    id: 6,
    name: "Frank Miller",
    email: "frank@example.com",
    department: "Engineering",
    role: "Junior Developer",
    salary: 60000,
    status: "active",
    location: "Austin",
    phone: "555-0106",
  },
  {
    id: 7,
    name: "Grace Lee",
    email: "grace@example.com",
    department: "Design",
    role: "UX Researcher",
    salary: 82000,
    status: "active",
    location: "Portland",
    phone: "555-0107",
  },
  {
    id: 8,
    name: "Henry Wilson",
    email: "henry@example.com",
    department: "Marketing",
    role: "Content Writer",
    salary: 55000,
    status: "inactive",
    location: "Denver",
    phone: "555-0108",
  },
  {
    id: 9,
    name: "Ivy Chen",
    email: "ivy@example.com",
    department: "Engineering",
    role: "Backend Developer",
    salary: 88000,
    status: "active",
    location: "Los Angeles",
    phone: "555-0109",
  },
  {
    id: 10,
    name: "Jack Thompson",
    email: "jack@example.com",
    department: "Sales",
    role: "Account Executive",
    salary: 72000,
    status: "active",
    location: "Miami",
    phone: "555-0110",
  },
  {
    id: 11,
    name: "Karen Martinez",
    email: "karen@example.com",
    department: "Design",
    role: "Product Designer",
    salary: 90000,
    status: "active",
    location: "New York",
    phone: "555-0111",
  },
  {
    id: 12,
    name: "Liam O'Brien",
    email: "liam@example.com",
    department: "Engineering",
    role: "DevOps Engineer",
    salary: 105000,
    status: "active",
    location: "San Francisco",
    phone: "555-0112",
  },
  {
    id: 13,
    name: "Mia Rodriguez",
    email: "mia@example.com",
    department: "Marketing",
    role: "SEO Specialist",
    salary: 62000,
    status: "active",
    location: "Chicago",
    phone: "555-0113",
  },
  {
    id: 14,
    name: "Noah Kim",
    email: "noah@example.com",
    department: "Engineering",
    role: "Frontend Developer",
    salary: 85000,
    status: "inactive",
    location: "Boston",
    phone: "555-0114",
  },
  {
    id: 15,
    name: "Olivia Taylor",
    email: "olivia@example.com",
    department: "Sales",
    role: "Sales Manager",
    salary: 98000,
    status: "active",
    location: "Seattle",
    phone: "555-0115",
  },
  {
    id: 16,
    name: "Paul Anderson",
    email: "paul@example.com",
    department: "Design",
    role: "Motion Designer",
    salary: 75000,
    status: "active",
    location: "Austin",
    phone: "555-0116",
  },
  {
    id: 17,
    name: "Quinn Foster",
    email: "quinn@example.com",
    department: "Engineering",
    role: "QA Engineer",
    salary: 70000,
    status: "active",
    location: "Portland",
    phone: "555-0117",
  },
  {
    id: 18,
    name: "Rachel Green",
    email: "rachel@example.com",
    department: "Marketing",
    role: "Brand Manager",
    salary: 92000,
    status: "active",
    location: "Denver",
    phone: "555-0118",
  },
  {
    id: 19,
    name: "Sam Harris",
    email: "sam@example.com",
    department: "Sales",
    role: "Business Developer",
    salary: 68000,
    status: "inactive",
    location: "Los Angeles",
    phone: "555-0119",
  },
  {
    id: 20,
    name: "Tina Patel",
    email: "tina@example.com",
    department: "Engineering",
    role: "Data Engineer",
    salary: 110000,
    status: "active",
    location: "Miami",
    phone: "555-0120",
  },
  {
    id: 21,
    name: "Uma Sharma",
    email: "uma@example.com",
    department: "Design",
    role: "Design Lead",
    salary: 115000,
    status: "active",
    location: "New York",
    phone: "555-0121",
  },
  {
    id: 22,
    name: "Victor Cruz",
    email: "victor@example.com",
    department: "Marketing",
    role: "Social Media Manager",
    salary: 58000,
    status: "active",
    location: "San Francisco",
    phone: "555-0122",
  },
  {
    id: 23,
    name: "Wendy Zhang",
    email: "wendy@example.com",
    department: "Engineering",
    role: "Security Engineer",
    salary: 125000,
    status: "active",
    location: "Chicago",
    phone: "555-0123",
  },
  {
    id: 24,
    name: "Xavier Moore",
    email: "xavier@example.com",
    department: "Sales",
    role: "Regional Manager",
    salary: 105000,
    status: "active",
    location: "Boston",
    phone: "555-0124",
  },
  {
    id: 25,
    name: "Yuki Tanaka",
    email: "yuki@example.com",
    department: "Design",
    role: "Illustrator",
    salary: 67000,
    status: "inactive",
    location: "Seattle",
    phone: "555-0125",
  },
  {
    id: 26,
    name: "Zoe Williams",
    email: "zoe@example.com",
    department: "Engineering",
    role: "ML Engineer",
    salary: 130000,
    status: "active",
    location: "Austin",
    phone: "555-0126",
  },
  {
    id: 27,
    name: "Aaron Scott",
    email: "aaron@example.com",
    department: "Marketing",
    role: "PR Specialist",
    salary: 64000,
    status: "active",
    location: "Portland",
    phone: "555-0127",
  },
  {
    id: 28,
    name: "Bella Rivera",
    email: "bella@example.com",
    department: "Sales",
    role: "Inside Sales Rep",
    salary: 52000,
    status: "active",
    location: "Denver",
    phone: "555-0128",
  },
  {
    id: 29,
    name: "Chris Evans",
    email: "chris@example.com",
    department: "Engineering",
    role: "Platform Engineer",
    salary: 115000,
    status: "inactive",
    location: "Los Angeles",
    phone: "555-0129",
  },
  {
    id: 30,
    name: "Diana Lopez",
    email: "diana@example.com",
    department: "Design",
    role: "Creative Director",
    salary: 140000,
    status: "active",
    location: "Miami",
    phone: "555-0130",
  },
  {
    id: 31,
    name: "Ethan Wright",
    email: "ethan@example.com",
    department: "Engineering",
    role: "Cloud Architect",
    salary: 145000,
    status: "active",
    location: "New York",
    phone: "555-0131",
  },
  {
    id: 32,
    name: "Fiona Clarke",
    email: "fiona@example.com",
    department: "Sales",
    role: "Enterprise Sales",
    salary: 88000,
    status: "active",
    location: "San Francisco",
    phone: "555-0132",
  },
  {
    id: 33,
    name: "George Adams",
    email: "george@example.com",
    department: "Marketing",
    role: "Growth Manager",
    salary: 95000,
    status: "active",
    location: "Chicago",
    phone: "555-0133",
  },
  {
    id: 34,
    name: "Hannah Baker",
    email: "hannah@example.com",
    department: "Design",
    role: "Brand Designer",
    salary: 72000,
    status: "inactive",
    location: "Boston",
    phone: "555-0134",
  },
  {
    id: 35,
    name: "Ian Cooper",
    email: "ian@example.com",
    department: "Engineering",
    role: "Site Reliability Engineer",
    salary: 118000,
    status: "active",
    location: "Seattle",
    phone: "555-0135",
  },
  {
    id: 36,
    name: "Julia Nelson",
    email: "julia@example.com",
    department: "Sales",
    role: "Partner Manager",
    salary: 82000,
    status: "active",
    location: "Austin",
    phone: "555-0136",
  },
  {
    id: 37,
    name: "Kevin Park",
    email: "kevin@example.com",
    department: "Engineering",
    role: "iOS Developer",
    salary: 92000,
    status: "active",
    location: "Portland",
    phone: "555-0137",
  },
  {
    id: 38,
    name: "Laura Hill",
    email: "laura@example.com",
    department: "Marketing",
    role: "Event Coordinator",
    salary: 54000,
    status: "active",
    location: "Denver",
    phone: "555-0138",
  },
  {
    id: 39,
    name: "Marcus Young",
    email: "marcus@example.com",
    department: "Design",
    role: "3D Artist",
    salary: 78000,
    status: "active",
    location: "Los Angeles",
    phone: "555-0139",
  },
  {
    id: 40,
    name: "Nina Ross",
    email: "nina@example.com",
    department: "Engineering",
    role: "Android Developer",
    salary: 90000,
    status: "inactive",
    location: "Miami",
    phone: "555-0140",
  },
  {
    id: 41,
    name: "Oscar Reed",
    email: "oscar@example.com",
    department: "Sales",
    role: "Channel Manager",
    salary: 76000,
    status: "active",
    location: "New York",
    phone: "555-0141",
  },
  {
    id: 42,
    name: "Penny Brooks",
    email: "penny@example.com",
    department: "Marketing",
    role: "Product Marketing",
    salary: 87000,
    status: "active",
    location: "San Francisco",
    phone: "555-0142",
  },
  {
    id: 43,
    name: "Ryan Hughes",
    email: "ryan@example.com",
    department: "Engineering",
    role: "Embedded Engineer",
    salary: 98000,
    status: "active",
    location: "Chicago",
    phone: "555-0143",
  },
  {
    id: 44,
    name: "Sofia Bell",
    email: "sofia@example.com",
    department: "Design",
    role: "Design Systems",
    salary: 95000,
    status: "active",
    location: "Boston",
    phone: "555-0144",
  },
  {
    id: 45,
    name: "Tyler Gray",
    email: "tyler@example.com",
    department: "Sales",
    role: "SDR Lead",
    salary: 65000,
    status: "inactive",
    location: "Seattle",
    phone: "555-0145",
  },
  {
    id: 46,
    name: "Ursula Price",
    email: "ursula@example.com",
    department: "Engineering",
    role: "Database Admin",
    salary: 102000,
    status: "active",
    location: "Austin",
    phone: "555-0146",
  },
  {
    id: 47,
    name: "Vincent Cole",
    email: "vincent@example.com",
    department: "Marketing",
    role: "Analytics Manager",
    salary: 89000,
    status: "active",
    location: "Portland",
    phone: "555-0147",
  },
  {
    id: 48,
    name: "Wanda Fisher",
    email: "wanda@example.com",
    department: "Design",
    role: "User Researcher",
    salary: 84000,
    status: "active",
    location: "Denver",
    phone: "555-0148",
  },
  {
    id: 49,
    name: "Xander Black",
    email: "xander@example.com",
    department: "Engineering",
    role: "VP of Engineering",
    salary: 180000,
    status: "active",
    location: "Los Angeles",
    phone: "555-0149",
  },
  {
    id: 50,
    name: "Yvonne Grant",
    email: "yvonne@example.com",
    department: "Sales",
    role: "VP of Sales",
    salary: 175000,
    status: "active",
    location: "Miami",
    phone: "555-0150",
  },
];

export function FullDemo() {
  const table = useDataTable({
    data,
    columns,
    plugins: [
      FilterPlugin.configure({ width: 320 }),
      ColumnControlPlugin.configure({ width: 280 }),
      FileExportPlugin.configure({
        filename: "employees",
        exporters: [CsvExporter, TsvExporter, JsonlExporter],
      }),
      RowDetailPlugin.configure({ width: 320 }),
    ],
  });

  useDataTableEvent(table, "row-click", (row) => {
    table.plugin.open("row-detail", { row });
  });

  return (
    <div
      style={{
        border: "1px solid #e5e7eb",
        borderRadius: "8px",
        overflow: "hidden",
      }}
    >
      <DataTable table={table} />
    </div>
  );
}
